apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-netmanager
  namespace: oakestra-network
  labels:
    app: netmanager
spec:
  selector:
    matchLabels:
      app: netmanager
  template:
    metadata:
      labels:
        app: netmanager
    spec:
      serviceAccountName: serviceaccount-oakestra-network
      hostPID: true
      #hostNetwork: true
      volumes:
      - name: host-netns
        hostPath:
          path: /var/run/netns
      - name: cni-bin
        hostPath:
          path: /opt/cni/bin
      initContainers:
      - name: init-cni-bin
        image: ghcr.io/jakobke/oakestra-cni:0.1-amd
        imagePullPolicy: Always
        command: ['sh', '-c', 'cp /app/oakestra /opt/cni/bin/']
        volumeMounts:
        - name: cni-bin
          mountPath: /opt/cni/bin
        securityContext:
          privileged: true
      containers:
      - name: node-netmanager
        image: ghcr.io/jakobke/oakestra-net-manager:0.2-amd
        imagePullPolicy: Always 
        ports:
        - containerPort: 6000
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          procMount: Default
          runAsUser: 0
          capabilities:
            add:
              - SYS_ADMIN
        volumeMounts:
        - name: host-netns
          mountPath: /var/run/netns
        env:
        - name: NODE_PORT
          value: "50103"
        - name: MOSQUITTO_SVC_SERVICE_PORT
          value: "30033"
        - name: MOSQUITTO_SVC_SERVICE_HOST
          value: "192.168.123.30"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: serviceaccount-oakestra-networks
  namespace: oakestra-network


--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterrole-oakestra-network
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods","nodes"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-role-binding-oakestra-network
  namespace: default
subjects:
- kind: ServiceAccount
  name: serviceaccount-oakestra-network
  namespace: oakestra-network
roleRef:
  kind: ClusterRole
  name: clusterrole-oakestra-network
  apiGroup: rbac.authorization.k8s.io


---

apiVersion: v1
kind: Service
metadata:
  name: netmanager-service
  namespace: oakestra-network
spec:
  type: NodePort
  selector:
    app: netmanager
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
      nodePort: 30010
