apiVersion: v1
kind: Pod
metadata:
  name: app1.appns.s3.snc.3
  annotations:
    k8s.v1.cni.cncf.io/networks: oakestra-cni
spec:
  containers:
  - name: samplepod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
    ports: 
    - containerPort: 80
