apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo
  namespace: oakestra-network
spec:
  accessModes:
    - ReadWriteOnce 
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  volumeName: mongodb-pv

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data/mongodb"